
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./index.scss";
import StoreProvider from "./StoreProvider";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getTheme() {
    const response = await fetch('http://localhost:8080/api/theme', {method: 'GET',
        credentials: "include", cache: "no-store"});
    return response.json()
}
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
   const theme =  await getTheme()
  return (
    <StoreProvider>
      <html lang="en">
        <body className={clsx(inter.className, {}, [theme])}>{children}</body>
      </html>
    </StoreProvider>
  );
}
